// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenSky.API;

namespace OpenSky.API.Migrations
{
    [DbContext(typeof(OpenSkyDbContext))]
    partial class OpenSkyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("OpenSky.API.Model.Airport", b =>
                {
                    b.Property<string>("ICAO")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("ICAO");

                    b.ToTable("Airports");
                });
#pragma warning restore 612, 618
        }
    }
}
