name: deploy docker hub DEV

on: [workflow_dispatch]

jobs:
  push_to_registry:
    if: contains(fromJson('["sushiat"]'), github.actor) && github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./OpenSky.API/Dockerfile
          push: true
          tags: openskyto/openskyapi:dev
